
server:
  http:
    timeout: 6
    hmac_header: ''
    hmac_secret: 'ab2316584873095f017f6dfa7a9415794f563fcc473eb3fe65b9167e37fd5a4b'
    bearer_token: 'ab2316584873095f017f6dfa7a9415794f563fcc473eb3fe65b9167e37fd5a4b'
    jwt:
      secret: 'ab2316584873095f017f6dfa7a9415794f563fcc473eb3fe65b9167e37fd5a4b'
      access_token_exp: 1
      refresh_token: true
      refresh_token_exp: 10
    allowed_origins: '*'
    allowed_headers: 'X-Requested-With,Content-Type,Authorization'
    allowed_methods: 'GET,POST,PUT,DELETE,HEAD'

  repo:
    driver: 'pgx'
    conn_str: 'host=testpghost user=test password=test123 dbname=woong_user port=5432 sslmode=disable TimeZone=Asia/Seoul'
    # used when driver is oci8, postgres, mssql...
    max_idle_conns: 25
    max_open_conns: 25
    conn_max_lifetime_in_min: 15

logger:
  json: true
  stdout: false
  file:
    name: 'logs/agent.log'
    max_size: 50
    max_backup: 100
    max_age: 31
    compressed: true
  level: 'debug'
