
logger:
  json: true
  stdout: true
  file:
    name: 'logs/agent.log'
    max_size: 50
    max_backup: 100
    max_age: 31
    compressed: true
  level: 'debug'

server:
  repo:
    driver: 'pgx'
    conn_str: 'host=testpghost user=test password=test123 dbname=woong_user port=5432 sslmode=disable TimeZone=Asia/Seoul'
    # used when driver is oci8, postgres, mssql...
    max_idle_conns: 25
    max_open_conns: 25
    conn_max_lifetime_in_min: 15

  grpc:
    timeout: 15
    healthcheck: false
    enforcement_policy:
      use: true
      min_time: 15
      permit_without_stream: true
    keep_alive:
      max_conn_idle: 300
      max_conn_age: 300
      max_conn_age_grace: 6
      time: 30
      timeout: 1

client:
  id_token_cookie: 'id_token'
  oauth2:
    integrated:
      openid_conf_url: 'https://127.0.0.1:5558/.well-known/openid-configuration'